export const PostsActionTypes = {
  GET_POSTS_REQ: 'GET_POSTS_REQ',
  GET_POSTS_RES: 'GET_POSTS_RES',
  CREATE_POST_REQ: 'CREATE_POST_REQ',
  CREATE_POST_RES: 'CREATE_POST_RES',
  EDIT_POST_REQ: 'EDIT_POST_REQ',
  EDIT_POST_RES: 'EDIT_POST_RES',
  SET_POST_RES: 'SET_POST_RES',
  DELETE_POST_REQ: 'DELETE_POST_REQ',
  DELETE_POST_RES: 'DELETE_POST_RES',
};

export const ProductsActionTypes = {
  GET_PRODUCTS_REQ: 'GET_PRODUCTS_REQ',
  GET_PRODUCTS_RES: 'GET_PRODUCTS_RES',
  CREATE_PRODUCT_REQ: 'CREATE_PRODUCT_REQ',
  CREATE_PRODUCT_RES: 'CREATE_PRODUCT_RES',
  EDIT_PRODUCT_REQ: 'EDIT_PRODUCT_REQ',
  EDIT_PRODUCT_RES: 'EDIT_PRODUCT_RES',
  SET_PRODUCT_RES: 'SET_PRODUCT_RES',
  DELETE_PRODUCT_REQ: 'DELETE_PRODUCT_REQ',
  DELETE_PRODUCT_RES: 'DELETE_PRODUCT_RES',
  DELETE_PRODUCT_IMAGE_REQ: 'DELETE_PRODUCT_IMAGE_REQ',
  DELETE_PRODUCT_IMAGE_RES: 'DELETE_PRODUCT_IMAGE_RES',
};

export const ThemesActionTypes = {
  GET_THEMES_REQ: 'GET_THEMES_REQ',
  GET_THEMES_RES: 'GET_THEMES_RES',
  CREATE_THEME_REQ: 'CREATE_THEME_REQ',
  CREATE_THEME_RES: 'CREATE_THEME_RES',
  EDIT_THEME_REQ: 'EDIT_THEME_REQ',
  EDIT_THEME_RES: 'EDIT_THEME_RES',
  SET_THEME_RES: 'SET_THEME_RES',
  DELETE_THEME_REQ: 'DELETE_THEME_REQ',
  DELETE_THEME_RES: 'DELETE_THEME_RES',
};

export const GalleryImagesActionTypes = {
  GET_GALLERY_IMAGES_REQ: 'GET_GALLERY_IMAGES_REQ',
  GET_GALLERY_IMAGES_RES: 'GET_GALLERY_IMAGES_RES',
  CREATE_GALLERY_IMAGES_REQ: 'CREATE_GALLERY_IMAGES_REQ',
  CREATE_GALLERY_IMAGES_RES: 'CREATE_GALLERY_IMAGES_RES',
  EDIT_GALLERY_IMAGES_REQ: 'EDIT_GALLERY_IMAGES_REQ',
  EDIT_GALLERY_IMAGES_RES: 'EDIT_GALLERY_IMAGES_RES',
  SET_GALLERY_IMAGES_RES: 'SET_GALLERY_IMAGES_RES',
  DELETE_GALLERY_IMAGES_REQ: 'DELETE_GALLERY_IMAGES_REQ',
  DELETE_GALLERY_IMAGES_RES: 'DELETE_GALLERY_IMAGES_RES',
};